### ISSUE TITLE
Minor UI/UX optimization

### ISSUE THREAD

**Issue by Lolagatorade** [ViperX7/Alpaca-Turbo#10]
Scaling / zoom is cumbersom. The chat box is abnormally large. Zoom to 70% is needed so the screen can properly display all elements. 
![image](https://user-images.githubusercontent.com/42100725/227343384-b9384cd8-2a84-4966-b2ee-5576cf4f08bb.png)

**Comment by ViperX7** [comment]
Not relevant anymore
