### ISSUE TITLE
No option to clear thread

### ISSUE THREAD

**Issue by Lolagatorade** [ViperX7/Alpaca-Turbo#11]
On the build no option to clear thread and history as earlier builds. 

![image](https://user-images.githubusercontent.com/42100725/227348673-1f5680ad-f623-4ab9-897e-95b3729e12b4.png)

**Comment by Lolagatorade** [comment]
After closing and opening the program once more the history remains saved. Behavior prior to this when the program closed the history was deleted.

**Comment by PleahMaCaka** [comment]
In my case the previous message was replaced with `\end{code}` - Windows 11

**Comment by Lolagatorade** [comment]
> In my case the previous message was replaced with `\end{code}` - Windows 11

For the previous build that happened to me a few times too. On this one not as much. Are you running the latest version? 

Would be nice to have version numbers too. Although little by little all those extra nice to have things add up to the complexity and nitpicky things devs have to keep in mind. They're doing a great job at managing this project.

**Comment by PleahMaCaka** [comment]
> > In my case the previous message was replaced with `\end{code}` - Windows 11
> 
> For the previous build that happened to me a few times too. On this one not as much. Are you running the latest version?
> 
> Would be nice to have version numbers too. Although little by little all those extra nice to have things add up to the complexity and nitpicky things devs have to keep in mind. They're doing a great job at managing this project.

I used pure clone of main branch [exactly here](https://github.com/ViperX7/Alpaca-Turbo/commit/bca7d9df1498fa0b65e5b00690283c2c206ab6a5)

**Comment by ViperX7** [comment]
Hey guys can you please pull latest branches I think it will solve all above discussed issues
