### ISSUE TITLE
Minor response issues

### ISSUE THREAD

**Issue by Lolagatorade** [ViperX7/Alpaca-Turbo#12]
It might just be the nature of the model but based on the initial Dalai release they had similar issues with random characters. Here it is similar when the thread gets longer and the history grows there seems to be a tendancy for random incoherant charecters to appear

Additionally take note at the ignored hello message initially. 
![image](https://user-images.githubusercontent.com/42100725/227351551-46e25d85-2a89-4674-ad65-c4a1bf8b0cba.png)

**Comment by trinca95** [comment]
i saw that characters too but they usually appear instead of ' like here in can't
