### ISSUE TITLE
Unsafe PID removal

### ISSUE THREAD

**Issue by J35ter** [ViperX7/Alpaca-Turbo#14]
Hi,

After an ungraceful exit (Restart of the computer or ), the pid file stays in the path, but there is no process under the PID.
When attempting to start alpaca_turbo, it tries to kill the non-existent PID in the file and crashes due to unhandled exception.

suggest the following fix for alpaca_turbo.py starting with line 310:

```  python
    if os.path.exists("./pid"):
        log.fatal("Already running another instance or dirty exit last time")
        with open("./pid") as file:
            pid = int(file.readline())
        log.info("Attempting to kill the process")
        try:
            os.kill(pid, signal.SIGTERM)
        except OSError:
            pass
        os.remove("./pid")
        log.info("Fixed the Issue Now Retry running")
```

This will make sure that the PID file is removed even when the process was not killed/available.
Alternately, you can first check for the PID by sending 
```python
    try:
        os.kill(pid, signal.SIGTERM)
    except OSError:
        os.remove("./pid")
```
And then try to kill the PID.

Sorry for the smartassing - love your project :)

**Comment by ViperX7** [comment]
Thanks for the feedback
made the necessary changes
