### ISSUE TITLE
win.exe crashes when trying to load a model

### ISSUE THREAD

**Issue by Pozaza** [ViperX7/Alpaca-Turbo#18]
### Problem:
After UI is launched I tried to load [alpaca 7b model](https://huggingface.co/Sosaka/Alpaca-native-4bit-ggml/blob/main/ggml-alpaca-7b-q4.bin), but when it's 100%, win.exe crashes and I can't generate anything.

### My specs:
- Windows 11 x64
- AMD A8-6500
- RAM 16GB 1666

**Comment by ViperX7** [comment]
hey Pzazz can you try rebuilding the binary

you just need to follow the instructions at https://github.com/Alpaca-Turbo/alpaca.cpp

build and replace the older binary with the newer one it should fix your issue

**Comment by Pozaza** [comment]
> hey Pzazz can you try rebuilding the binary
> 
> you just need to follow the instructions at https://github.com/Alpaca-Turbo/alpaca.cpp
> 
> build and replace the older binary with the newer one it should fix your issue

Still doesn't work. I compiled the `chat.exe` file, renamed it to `win.exe` and replaced the old file with it and it still crashes.. Model now "loads" in less than a second and crashes in the same time

**Comment by kickvent** [comment]
Hello! Any fix? I would be interested.

**Comment by Showgofar** [comment]
try remove cyrillic from path

**Comment by Pozaza** [comment]
already tried
