### ISSUE TITLE
Support reverse prompting (-r flag in llama.cpp)

### ISSUE THREAD

**Issue by jhayesdev** [ViperX7/Alpaca-Turbo#53]
Particularly for Vicuna you need to be able to set the reverse prompt so it doesn't continue blathering on after it's already answered you. Default llama.cpp instruct mode (-ins) uses "### Instruction:
" as reverse prompt, but Vicuna needs "### Human:".

I'm not sure that reverse prompts are implemented at all right now, please correct if wrong and I'm not using it right. If author is not interested in doing it, I will have 3 weeks of free time coming up and I'd be more than happy to do a PR when I can dig into it.

**Comment by ViperX7** [comment]
The latest release adds support for reverse prompting 

@jhayesdev  thanks for the offer I would like to checkout any suggestions or PR that will improve the project
